window.PREP_SEED = {
  exams: [
    {ExamID:'AP_EAPCET_E',ExamName:'AP EAPCET – Engineering',Category:'Engineering',Stream:'Engineering',ShortName:'EAPCET-E',Description:'Complete syllabus-first self preparation for AP EAPCET Engineering.',DurationMin:180,TotalQuestions:160,TotalMarks:160,NegativeMarking:'No',OfficialURL:'https://cets.apsche.ap.gov.in/EAPCET/'},
    {ExamID:'AP_EAPCET_AP',ExamName:'AP EAPCET – Agriculture & Pharmacy',Category:'Agriculture & Pharmacy',Stream:'Bi.P.C.',ShortName:'EAPCET-AP',Description:'Complete topic-wise self preparation for AP EAPCET Agriculture & Pharmacy.',DurationMin:180,TotalQuestions:160,TotalMarks:160,NegativeMarking:'No',OfficialURL:'https://cets.apsche.ap.gov.in/EAPCET/'},
    {ExamID:'NEET_UG',ExamName:'NEET UG',Category:'Medical',Stream:'UG Medical',ShortName:'NEET',Description:'Physics, Chemistry and Biology self preparation with topic-linked MCQ quizzes.',DurationMin:180,TotalQuestions:180,TotalMarks:720,NegativeMarking:'+4 / -1',OfficialURL:'https://neet.nta.nic.in/'},
    {ExamID:'AP_POLYCET',ExamName:'AP POLYCET',Category:'Polytechnic',Stream:'Diploma Entrance',ShortName:'POLYCET',Description:'Complete Mathematics, Physics and Chemistry topic-wise self preparation.',DurationMin:120,TotalQuestions:120,TotalMarks:120,NegativeMarking:'No',OfficialURL:'https://polycetap.nic.in/'}
  ],
  syllabus: [
    // AP EAPCET Engineering — Mathematics
    ['EEM001','AP_EAPCET_E','Mathematics','Algebra','Functions'],
    ['EEM002','AP_EAPCET_E','Mathematics','Algebra','Mathematical Induction'],
    ['EEM003','AP_EAPCET_E','Mathematics','Algebra','Matrices'],
    ['EEM004','AP_EAPCET_E','Mathematics','Algebra','Complex Numbers'],
    ['EEM005','AP_EAPCET_E','Mathematics','Algebra','Permutations and Combinations'],
    ['EEM006','AP_EAPCET_E','Mathematics','Algebra','Binomial Theorem'],
    ['EEM007','AP_EAPCET_E','Mathematics','Trigonometry','Trigonometric Ratios and Equations'],
    ['EEM008','AP_EAPCET_E','Mathematics','Coordinate Geometry','Straight Lines'],
    ['EEM009','AP_EAPCET_E','Mathematics','Coordinate Geometry','Circle'],
    ['EEM010','AP_EAPCET_E','Mathematics','Coordinate Geometry','Conic Sections'],
    ['EEM011','AP_EAPCET_E','Mathematics','Calculus','Limits and Continuity'],
    ['EEM012','AP_EAPCET_E','Mathematics','Calculus','Differentiation and Applications'],
    ['EEM013','AP_EAPCET_E','Mathematics','Calculus','Integration'],
    ['EEM014','AP_EAPCET_E','Mathematics','Calculus','Differential Equations'],
    ['EEM015','AP_EAPCET_E','Mathematics','Vectors & 3D','Vector Algebra'],
    ['EEM016','AP_EAPCET_E','Mathematics','Probability','Probability and Random Variables'],
    // AP EAPCET Engineering — Physics
    ['EEP001','AP_EAPCET_E','Physics','Mechanics','Units and Measurements'],
    ['EEP002','AP_EAPCET_E','Physics','Mechanics','Motion in a Straight Line'],
    ['EEP003','AP_EAPCET_E','Physics','Mechanics','Motion in a Plane'],
    ['EEP004','AP_EAPCET_E','Physics','Mechanics','Laws of Motion'],
    ['EEP005','AP_EAPCET_E','Physics','Mechanics','Work Energy and Power'],
    ['EEP006','AP_EAPCET_E','Physics','Mechanics','Rotational Motion'],
    ['EEP007','AP_EAPCET_E','Physics','Mechanics','Gravitation'],
    ['EEP008','AP_EAPCET_E','Physics','Thermal Physics','Thermodynamics'],
    ['EEP009','AP_EAPCET_E','Physics','Oscillations & Waves','Oscillations and Waves'],
    ['EEP010','AP_EAPCET_E','Physics','Electricity','Electrostatics'],
    ['EEP011','AP_EAPCET_E','Physics','Electricity','Current Electricity'],
    ['EEP012','AP_EAPCET_E','Physics','Magnetism','Magnetic Effects and Magnetism'],
    ['EEP013','AP_EAPCET_E','Physics','Magnetism','Electromagnetic Induction and AC'],
    ['EEP014','AP_EAPCET_E','Physics','Optics & Modern','Ray and Wave Optics'],
    ['EEP015','AP_EAPCET_E','Physics','Optics & Modern','Dual Nature Atoms and Nuclei'],
    ['EEP016','AP_EAPCET_E','Physics','Optics & Modern','Semiconductor Electronics'],
    // AP EAPCET Engineering — Chemistry
    ['EEC001','AP_EAPCET_E','Chemistry','Physical Chemistry','Atomic Structure'],
    ['EEC002','AP_EAPCET_E','Chemistry','Physical Chemistry','Chemical Bonding'],
    ['EEC003','AP_EAPCET_E','Chemistry','Physical Chemistry','Thermodynamics'],
    ['EEC004','AP_EAPCET_E','Chemistry','Physical Chemistry','Equilibrium'],
    ['EEC005','AP_EAPCET_E','Chemistry','Physical Chemistry','Solutions'],
    ['EEC006','AP_EAPCET_E','Chemistry','Physical Chemistry','Electrochemistry'],
    ['EEC007','AP_EAPCET_E','Chemistry','Physical Chemistry','Chemical Kinetics'],
    ['EEC008','AP_EAPCET_E','Chemistry','Inorganic Chemistry','p-Block Elements'],
    ['EEC009','AP_EAPCET_E','Chemistry','Inorganic Chemistry','d and f Block Elements'],
    ['EEC010','AP_EAPCET_E','Chemistry','Inorganic Chemistry','Coordination Compounds'],
    ['EEC011','AP_EAPCET_E','Chemistry','Organic Chemistry','Basic Principles of Organic Chemistry'],
    ['EEC012','AP_EAPCET_E','Chemistry','Organic Chemistry','Hydrocarbons'],
    ['EEC013','AP_EAPCET_E','Chemistry','Organic Chemistry','Haloalkanes and Haloarenes'],
    ['EEC014','AP_EAPCET_E','Chemistry','Organic Chemistry','Alcohols Phenols and Ethers'],
    ['EEC015','AP_EAPCET_E','Chemistry','Organic Chemistry','Carbonyl Compounds and Carboxylic Acids'],
    ['EEC016','AP_EAPCET_E','Chemistry','Organic Chemistry','Amines and Biomolecules'],

    // AP EAPCET Agriculture & Pharmacy — Botany
    ['APB001','AP_EAPCET_AP','Botany','Diversity in Living World','The Living World'],
    ['APB002','AP_EAPCET_AP','Botany','Diversity in Living World','Biological Classification'],
    ['APB003','AP_EAPCET_AP','Botany','Diversity in Living World','Plant Kingdom'],
    ['APB004','AP_EAPCET_AP','Botany','Structural Organisation','Morphology of Flowering Plants'],
    ['APB005','AP_EAPCET_AP','Botany','Structural Organisation','Anatomy of Flowering Plants'],
    ['APB006','AP_EAPCET_AP','Botany','Cell Biology','Cell Structure and Function'],
    ['APB007','AP_EAPCET_AP','Botany','Plant Physiology','Photosynthesis'],
    ['APB008','AP_EAPCET_AP','Botany','Plant Physiology','Respiration and Plant Growth'],
    ['APB009','AP_EAPCET_AP','Botany','Reproduction','Sexual Reproduction in Flowering Plants'],
    ['APB010','AP_EAPCET_AP','Botany','Genetics','Principles of Inheritance and Variation'],
    ['APB011','AP_EAPCET_AP','Botany','Genetics','Molecular Basis of Inheritance'],
    ['APB012','AP_EAPCET_AP','Botany','Biotechnology','Biotechnology Principles and Applications'],
    ['APB013','AP_EAPCET_AP','Botany','Ecology','Organisms and Populations'],
    ['APB014','AP_EAPCET_AP','Botany','Ecology','Ecosystem Biodiversity and Conservation'],
    // AP EAPCET Agriculture & Pharmacy — Zoology
    ['APZ001','AP_EAPCET_AP','Zoology','Animal Diversity','Animal Kingdom'],
    ['APZ002','AP_EAPCET_AP','Zoology','Structural Organisation','Structural Organisation in Animals'],
    ['APZ003','AP_EAPCET_AP','Zoology','Human Physiology','Digestion and Absorption'],
    ['APZ004','AP_EAPCET_AP','Zoology','Human Physiology','Breathing and Exchange of Gases'],
    ['APZ005','AP_EAPCET_AP','Zoology','Human Physiology','Body Fluids and Circulation'],
    ['APZ006','AP_EAPCET_AP','Zoology','Human Physiology','Excretory Products and Elimination'],
    ['APZ007','AP_EAPCET_AP','Zoology','Human Physiology','Neural and Chemical Coordination'],
    ['APZ008','AP_EAPCET_AP','Zoology','Reproduction','Human Reproduction'],
    ['APZ009','AP_EAPCET_AP','Zoology','Reproduction','Reproductive Health'],
    ['APZ010','AP_EAPCET_AP','Zoology','Genetics & Evolution','Evolution'],
    ['APZ011','AP_EAPCET_AP','Zoology','Human Welfare','Human Health and Disease'],
    ['APZ012','AP_EAPCET_AP','Zoology','Human Welfare','Microbes in Human Welfare'],
    // AP EAPCET AP — Physics/Chemistry core
    ['APP001','AP_EAPCET_AP','Physics','Mechanics','Units and Measurements'],
    ['APP002','AP_EAPCET_AP','Physics','Mechanics','Kinematics and Laws of Motion'],
    ['APP003','AP_EAPCET_AP','Physics','Mechanics','Work Energy Power and Gravitation'],
    ['APP004','AP_EAPCET_AP','Physics','Thermal Physics','Thermodynamics and Kinetic Theory'],
    ['APP005','AP_EAPCET_AP','Physics','Waves','Oscillations and Waves'],
    ['APP006','AP_EAPCET_AP','Physics','Electricity','Electrostatics and Current Electricity'],
    ['APP007','AP_EAPCET_AP','Physics','Magnetism','Magnetism EMI and AC'],
    ['APP008','AP_EAPCET_AP','Physics','Optics & Modern','Optics and Modern Physics'],
    ['APC001','AP_EAPCET_AP','Chemistry','Physical Chemistry','Atomic Structure and Chemical Bonding'],
    ['APC002','AP_EAPCET_AP','Chemistry','Physical Chemistry','Thermodynamics and Equilibrium'],
    ['APC003','AP_EAPCET_AP','Chemistry','Physical Chemistry','Solutions Electrochemistry and Kinetics'],
    ['APC004','AP_EAPCET_AP','Chemistry','Inorganic Chemistry','p-Block Elements'],
    ['APC005','AP_EAPCET_AP','Chemistry','Inorganic Chemistry','d/f Block and Coordination Compounds'],
    ['APC006','AP_EAPCET_AP','Chemistry','Organic Chemistry','Organic Chemistry Principles and Hydrocarbons'],
    ['APC007','AP_EAPCET_AP','Chemistry','Organic Chemistry','Halo Compounds Alcohols Phenols and Ethers'],
    ['APC008','AP_EAPCET_AP','Chemistry','Organic Chemistry','Carbonyls Amines and Biomolecules'],

    // NEET UG
    ['NEP001','NEET_UG','Physics','Mechanics','Physics and Measurement'],
    ['NEP002','NEET_UG','Physics','Mechanics','Kinematics'],
    ['NEP003','NEET_UG','Physics','Mechanics','Laws of Motion'],
    ['NEP004','NEET_UG','Physics','Mechanics','Work Energy and Power'],
    ['NEP005','NEET_UG','Physics','Mechanics','Rotational Motion'],
    ['NEP006','NEET_UG','Physics','Mechanics','Gravitation'],
    ['NEP007','NEET_UG','Physics','Thermal Physics','Thermodynamics and Kinetic Theory'],
    ['NEP008','NEET_UG','Physics','Waves','Oscillations and Waves'],
    ['NEP009','NEET_UG','Physics','Electricity','Electrostatics'],
    ['NEP010','NEET_UG','Physics','Electricity','Current Electricity'],
    ['NEP011','NEET_UG','Physics','Magnetism','Magnetic Effects and Magnetism'],
    ['NEP012','NEET_UG','Physics','Magnetism','EMI and Alternating Current'],
    ['NEP013','NEET_UG','Physics','Optics & Modern','Optics'],
    ['NEP014','NEET_UG','Physics','Optics & Modern','Dual Nature Atoms and Nuclei'],
    ['NEP015','NEET_UG','Physics','Optics & Modern','Electronic Devices'],
    ['NEC001','NEET_UG','Chemistry','Physical Chemistry','Some Basic Concepts and Atomic Structure'],
    ['NEC002','NEET_UG','Chemistry','Physical Chemistry','Chemical Bonding and Molecular Structure'],
    ['NEC003','NEET_UG','Chemistry','Physical Chemistry','Chemical Thermodynamics'],
    ['NEC004','NEET_UG','Chemistry','Physical Chemistry','Solutions and Equilibrium'],
    ['NEC005','NEET_UG','Chemistry','Physical Chemistry','Redox Electrochemistry and Kinetics'],
    ['NEC006','NEET_UG','Chemistry','Inorganic Chemistry','Periodicity and p-Block Elements'],
    ['NEC007','NEET_UG','Chemistry','Inorganic Chemistry','d/f Block and Coordination Compounds'],
    ['NEC008','NEET_UG','Chemistry','Organic Chemistry','Basic Principles of Organic Chemistry'],
    ['NEC009','NEET_UG','Chemistry','Organic Chemistry','Hydrocarbons and Halo Compounds'],
    ['NEC010','NEET_UG','Chemistry','Organic Chemistry','Oxygen and Nitrogen Compounds'],
    ['NEC011','NEET_UG','Chemistry','Organic Chemistry','Biomolecules and Practical Chemistry'],
    ['NEB001','NEET_UG','Biology','Diversity','Diversity in Living World'],
    ['NEB002','NEET_UG','Biology','Structural Organisation','Structural Organisation in Animals and Plants'],
    ['NEB003','NEET_UG','Biology','Cell Biology','Cell Structure and Function'],
    ['NEB004','NEET_UG','Biology','Plant Physiology','Plant Physiology'],
    ['NEB005','NEET_UG','Biology','Human Physiology','Human Physiology'],
    ['NEB006','NEET_UG','Biology','Reproduction','Reproduction'],
    ['NEB007','NEET_UG','Biology','Genetics & Evolution','Genetics and Evolution'],
    ['NEB008','NEET_UG','Biology','Human Welfare','Biology and Human Welfare'],
    ['NEB009','NEET_UG','Biology','Biotechnology','Biotechnology and Its Applications'],
    ['NEB010','NEET_UG','Biology','Ecology','Ecology and Environment'],

    // AP POLYCET
    ['POLY001','AP_POLYCET','Mathematics','Number System','Real Numbers'],
    ['POLY002','AP_POLYCET','Mathematics','Number System','Sets'],
    ['POLY003','AP_POLYCET','Mathematics','Number System','Polynomials'],
    ['POLY004','AP_POLYCET','Mathematics','Algebra','Linear Equations'],
    ['POLY005','AP_POLYCET','Mathematics','Algebra','Quadratic Equations'],
    ['POLY006','AP_POLYCET','Mathematics','Algebra','Progressions'],
    ['POLY007','AP_POLYCET','Mathematics','Geometry','Coordinate Geometry'],
    ['POLY008','AP_POLYCET','Mathematics','Geometry','Similar Triangles'],
    ['POLY009','AP_POLYCET','Mathematics','Geometry','Circles'],
    ['POLY010','AP_POLYCET','Mathematics','Geometry','Tangents and Secants'],
    ['POLY011','AP_POLYCET','Mathematics','Trigonometry','Trigonometry'],
    ['POLY012','AP_POLYCET','Mathematics','Trigonometry','Applications of Trigonometry'],
    ['POLY013','AP_POLYCET','Mathematics','Mensuration','Surface Areas and Volumes'],
    ['POLY014','AP_POLYCET','Mathematics','Statistics','Statistics'],
    ['POLY015','AP_POLYCET','Mathematics','Statistics','Probability'],
    ['POLY016','AP_POLYCET','Physics','Mechanics','Motion'],
    ['POLY017','AP_POLYCET','Physics','Mechanics','Force'],
    ['POLY018','AP_POLYCET','Physics','Mechanics','Work and Energy'],
    ['POLY019','AP_POLYCET','Physics','Optics','Reflection of Light'],
    ['POLY020','AP_POLYCET','Physics','Optics','Refraction of Light'],
    ['POLY021','AP_POLYCET','Physics','Optics','Human Eye'],
    ['POLY022','AP_POLYCET','Physics','Electricity','Electric Current'],
    ['POLY023','AP_POLYCET','Physics','Electricity','Electromagnetism'],
    ['POLY024','AP_POLYCET','Physics','General Physics','Sources of Energy'],
    ['POLY025','AP_POLYCET','Chemistry','Matter','Chemical Reactions and Equations'],
    ['POLY026','AP_POLYCET','Chemistry','Matter','Acids Bases and Salts'],
    ['POLY027','AP_POLYCET','Chemistry','Materials','Metals and Non-metals'],
    ['POLY028','AP_POLYCET','Chemistry','Materials','Carbon and its Compounds'],
    ['POLY029','AP_POLYCET','Chemistry','Classification','Periodic Classification of Elements']
  ] .map((x,i)=>({SyllabusID:x[0],ExamID:x[1],Subject:x[2],Chapter:x[3],Topic:x[4],UnitOrder:1,ChapterOrder:i+1,TopicOrder:1,Active:true,'MCQ Quiz':(x[1]==='AP_EAPCET_E'&&i<5)?'https://script.google.com/macros/s/AKfycbxeD4196ueVAWsgOmmhIyD8x98W-9bBo-wTwZmq_BJ31xTu7N9FWh8CYZsgWBp5P15Y/exec?topic=Computer%20Fundamentals%20-%20Part-%20'+(i+1):''})),
  resources: []
};
